# Generated by Django 3.2.5 on 2022-03-01 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(null=True, verbose_name='النقاط')),
                ('amount', models.IntegerField(verbose_name='قيمة الحوالي')),
                ('receipt_number', models.CharField(error_messages={'unique': 'تم ارسال رقم هذا الايصال مسبقاً.'}, max_length=20, unique=True, verbose_name='رقم الايصال')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
