# Generated by Django 3.2.5 on 2022-03-01 19:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expanse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('discription', models.CharField(max_length=300)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('library_fee', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddField(
            model_name='transfer',
            name='library_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.IntegerField(verbose_name='قيمة الحوالة'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='receipt_number',
            field=models.CharField(blank=True, error_messages={'unique': 'تم ارسال رقم هذا الايصال مسبقاً.'}, max_length=20, unique=True, verbose_name='رقم الايصال'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main2.library'),
        ),
    ]
