# Generated by Django 3.2.5 on 2022-03-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0002_auto_20220301_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='receipt_number',
            field=models.CharField(blank=True, error_messages={'unique': 'تم ارسال رقم هذا الايصال مسبقاً.'}, max_length=20, verbose_name='رقم الايصال'),
        ),
    ]
