# Generated by Django 3.2.5 on 2022-03-07 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main2', '0003_alter_transfer_receipt_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlharamTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='قيمة الحوالة')),
                ('receipt_number', models.IntegerField(error_messages={'unique': 'تم ارسال رقم هذا الايصال مسبقاً.'}, max_length=20, unique=True, verbose_name='رقم الايصال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='قيمة الحوالة')),
                ('library_fee', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
        migrations.AddField(
            model_name='librarytransfer',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main2.library'),
        ),
        migrations.AddField(
            model_name='librarytransfer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
