# Generated by Django 3.2.5 on 2022-03-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0004_auto_20220307_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alharamtransfer',
            name='receipt_number',
            field=models.IntegerField(error_messages={'unique': 'تم ارسال رقم هذا الايصال مسبقاً.'}, unique=True, verbose_name='رقم الايصال'),
        ),
    ]
