# Generated by Django 3.2.5 on 2022-03-07 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main2', '0005_alter_alharamtransfer_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='alharamtransfer',
            name='points',
            field=models.IntegerField(default=0, verbose_name='النقاط'),
        ),
        migrations.AddField(
            model_name='librarytransfer',
            name='points',
            field=models.IntegerField(default=0, verbose_name='النقاط'),
        ),
        migrations.AlterField(
            model_name='alharamtransfer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='librarytransfer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
