# Generated by Django 3.2.5 on 2022-03-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0006_auto_20220307_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarytransfer',
            name='library_fee',
        ),
    ]
