# Generated by Django 3.2.5 on 2022-03-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0007_remove_librarytransfer_library_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarytransfer',
            old_name='library',
            new_name='library_id',
        ),
    ]
