# Generated by Django 3.2.5 on 2022-03-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0011_expanse_titles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expanse',
            old_name='titles',
            new_name='title',
        ),
    ]
