# Generated by Django 3.2.5 on 2022-03-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0012_rename_titles_expanse_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expanse',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
