# Generated by Django 3.2.5 on 2022-04-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0013_alter_expanse_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField()),
                ('total_income', models.IntegerField()),
                ('total_expanses', models.IntegerField()),
                ('total_paid_expanses', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='expanse',
            name='payment',
            field=models.CharField(choices=[('P', 'Paid'), ('U', 'Unpaid')], default='U', max_length=1),
        ),
    ]
