# Generated by Django 3.2.5 on 2022-04-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0014_auto_20220419_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expanse',
            old_name='payment',
            new_name='paid',
        ),
        migrations.AlterField(
            model_name='record',
            name='total_expanses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_paid_expanses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
