# Generated by Django 3.2.5 on 2022-04-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0015_auto_20220419_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='name',
            field=models.CharField(default='record', max_length=7, unique=True),
        ),
    ]
