# Generated by Django 3.2.5 on 2022-04-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0016_record_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expanse',
            name='status',
            field=models.CharField(choices=[('C', 'Confirmed'), ('U', 'Unconfirmed')], default='U', max_length=1),
        ),
    ]
